### ISSUE TITLE
DIoException [unknown]: null Error: HttpException: Content size below specified contentLength

### ISSUE THREAD

**Issue by selfhoster1312** [localsend/localsend#1054]
### Describe the bug

Transfer of video did not work from iPhone to desktop. Error shown on iPhone:

```
DIoException [unknown]: null Error: HttpException: Content size below specified contentLength
bytes written but expeced 817271.
```

On other side progress shown is 0. Canceling the download produces no visible error, but does not cancel the download and go back to main menu.

Some further transfers worked, but produces errors on receiving desktop side:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
#0      DBusClient._callMethod (package:dbus/src/dbus_client.dart:1120)
<asynchronous suspension>
#1      DBusClient.callMethod (package:dbus/src/dbus_client.dart:621)
<asynchronous suspension>
#2      WakelockPlusLinuxPlugin.toggle (package:wakelock_plus/src/wakelock_plus_linux_plugin.dart:40)
<asynchronous suspension>
```

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      ConnectivityPlusLinuxPlugin._startListenConnectivity (package:connectivity_plus/src/connectivity_plus_linux.dart:68)
<asynchronous suspension>
```

### To reproduce

Not sure.

### Expected behavior

Should work.

### Desktop (please complete the following information)

- OS: GNU/Linux
- Version: 1.13.1 (Flatpak)

### Smartphone (please complete the following information)

- OS: iOS v13.1.2
- Version: v1.13.2

**Comment by ehte92** [comment]
I'm facing the same issue. Trying to transfer an apk file of around 1.9 gb from iPhone to an android device.

**Comment by jollypunch** [comment]
This happened to me when transfering a file multiple times. The file was overwritten on the sender machine, but the details were not updated. LocalSend was showing it as 11mb while it became 14mb. Reselecting the file to send updated the size and sent it correctly.

Sending from Win10 to MacOS.

**Comment by RenSch89** [comment]
I had the same issue by trying to transfer ubuntu.iso file (5GiB) from one to another linux device. But the file had odd access rights - a program restricted the file to be only readable to me as user. Therefor I got the error "Content size below specified contentLength" after downloading the iso again, it worked fine. Also all other big files with a vary of file extensions (.deb, .mp4, .jpeg...) and sizes (from 100MiB to 10GiB) worked fine.

Maybe you have the same problem?
