### ISSUE TITLE
Bug report - Error on startup after last update.

### ISSUE THREAD

**Issue by Yolakalemowa** [localsend/localsend#1589]
### Describe the bug

Hello,

I have LS downloaded through chocolatey. After updating to v1.15.3, when I open it, I'm greeted with a screen with the following error:

LocalSend 1.15.3 (53)

Error: PathAccessException: Cannot open file, path = 'C:\ProgramData\chocolatey\lib\localsend.portable\tools\settings.json' (OS Error: Access is denied.
, errno = 5)

#0      _Link.throwIfError (dart:io/link.dart:254)
#1      _File.openSync (dart:io/file_impl.dart:490)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:644)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:668)
#4      SharedPreferencesFile._write (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:72)
#5      SharedPreferencesFile.setValue (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:63)
#6      PersistenceService.initialize (package:localsend_app/provider/persistence_provider.dart:122)
<asynchronous suspension>
#7      preInit (package:localsend_app/config/init.dart:60)
<asynchronous suspension>
#8      main (package:localsend_app/main.dart:23)
<asynchronous suspension>

Is it an error on my end? It was working fine before.

### To reproduce

1. Have LS 1.15.2 downloaded from chocolatey
2. upgrade to latest 1.15.3 through chocolatey 
3. open local send
4. See error message abovev

### Expected behavior

start normally 

### Screenshots

![image](https://github.com/user-attachments/assets/cce82c5a-5022-43ba-912e-6d9d0bae7200)

### Desktop (please complete the following information)

Using Win10.
Chocolatey

**Comment by Tienisto** [comment]
Is the executable located in the same directory as `settings.json`?
If you delete `settings.json`, then it should fallback to a location in AppData. But I don't know why it doesn't have write access though...

Maybe @brogers5 knows more

**Comment by brogers5** [comment]
I'm surprised this hasn't been reported earlier. Looks like v1.13.0 started including `settings.json` in the portable packaging, which would trigger this behavior.

This is because Chocolatey locks down the write permissions of `C:\ProgramData\chocolatey` for non-Administrators as part of its installation process, and the contents of the extracted ZIP archive live within here. Had this same problem come up recently in another package I maintain.

A workaround would be to run LocalSend as administrator to grant the process the user token it needs to write here.

I'll need to tweak the portable package to better support this use case for non-elevated users. Most likely this will involve implementing support for the [`ChocolateyToolsLocation` environment variable](https://docs.chocolatey.org/en-us/create/functions/get-toolslocation/) to enable better control of where it gets extracted.

FYI, the Chocolatey packages are not maintained here, and any issues with them should be directed to the appropriate repository (in this case, the portable package):

https://github.com/brogers5/chocolatey-package-localsend
https://github.com/brogers5/chocolatey-package-localsend.install
https://github.com/brogers5/chocolatey-package-localsend.portable

**Comment by CullPen** [comment]
# Troubleshooting LocalSend Access Error

## Error Description

When opening LocalSend after updating to version 1.15.3, you encounter the following error:

```
Error: PathAccessException: Cannot open file, path = 'C:\ProgramData\chocolatey\lib\localsend.portable\tools\settings.json' (OS Error: Access is denied., errno = 5)
#0 _Link.throwIfError (dart:io/link.dart:254)
#1 _File.openSync (dart:io/file_impl.dart:490)
#2 _File.writeAsBytesSync (dart:io/file_impl.dart:644)
#3 _File.writeAsStringSync (dart:io/file_impl.dart:668)
#4 SharedPreferencesFile._write (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:72)
#5 SharedPreferencesFile.setValue (package:localsend_app/util/shared_preferences/shared_preferences_file.dart:63)
#6 PersistenceService.initialize (package:localsend_app/provider/persistence_provider.dart:122)
#7 preInit (package:localsend_app/config/init.dart:60)
#8 main (package:localsend_app/main.dart:23)
```

## Troubleshooting Steps

### Step 1: Changing File Permissions

1. Navigate to `C:\ProgramData\chocolatey\lib\localsend.portable\tools`.
2. Right-click on the `settings.json` file and select `Properties`.
3. Go to the `Security` tab.
4. Click on `Edit` to change permissions.
5. Select the user running the application and ensure that the user has `Read` and `Write` permissions.
6. Apply the changes.

### Step 2: Running the Application as Administrator

1. Right-click on the LocalSend application shortcut.
2. Select `Run as administrator`.

### Step 3: Checking Antivirus/Firewall Settings

1. Open your antivirus or firewall software.
2. Check the logs to see if it has blocked access to `settings.json`.
3. If it has, create an exception for the LocalSend application or the specific file path.

### Step 4: Reinstall LocalSend

1. Open Command Prompt as an administrator.
2. Uninstall LocalSend:
   ```bash
   choco uninstall localsend.portable
   ```
3. Reinstall LocalSend:
   ```bash
   choco install localsend.portable
   ```

If the issue persists after following these steps, please let me know, and we can explore further troubleshooting options. Additionally, if you have any specific code changes or configuration that you want to address, please share the details.

**Comment by slrgt** [comment]
i got this error and after running it as administrator now when it auto starts i cant minimize or close the window

**Comment by liayn** [comment]
https://github.com/brogers5/chocolatey-package-localsend.portable/issues/1#issuecomment-2264446673
concludes this is a bug in localsend

**Comment by Tienisto** [comment]
What path does it say without administrator run? @slrgt

**Comment by brogers5** [comment]
> [brogers5/chocolatey-package-localsend.portable#1 (comment)](https://github.com/brogers5/chocolatey-package-localsend.portable/issues/1#issuecomment-2264446673) concludes this is a bug in localsend

Just wanted to clarify this applies only to @slrgt's comments. The parent issue is specific to the Chocolatey package and should not require any changes in LocalSend. This will be addressed with the next package version.

**Comment by brogers5** [comment]
I've just pushed a package fix version.
