### ISSUE TITLE
Cannot send files to Linux Phone

### ISSUE THREAD

**Issue by vogonwann** [localsend/localsend#1800]
### Describe the bug

I cannot send files from any other device on the network to my Linux Phone. I've opened port 53317 on the phone, but to no avail. Linux phone is using the same version of LocalSend as Linux Desktop (installed from flathub)

### To reproduce

1. Go to LocalSend on your computer or Android phone
2. Try to send anything to Linux phone
3. Connection timeout (Error)

### Expected behavior

Files/Folders are sent to the Linux Phone

### Desktop (please complete the following information)

- OS: Fedora 41

### Smartphone (please complete the following information)

- OnePlus 6: PostmarketOS Edge

**Comment by Bazixv13** [comment]
maybe its the firewall config?

**Comment by vogonwann** [comment]
I have disabled the firewall but still no. Tried on three different phones. Is there a log somewhere that I can see or post here?

**Comment by vogonwann** [comment]
```
DioException [connection timeout]: The request connection took longer than 720:00:00.000000 and it was aborted. To get rid of this exception, try raising the RequestOptions.connectTimeout above the duration of 720:00:00.000000 or improve the response time of the server.
Error: SocketException: Connection timed out (OS Error: Connection timed out, errno = 110), address = 192.168.1.33, port = 34406
```

**Comment by eboye** [comment]
I've got the same issue. Xiaomi Mi A1 (Tissot) with postmarketOS v23.12 aarch64

**Comment by realth000** [comment]
Is the port in listening state?

```bash
sudo lsof -i -P -n | grep 53317
```
or other network transfer tools may not work either:

```bash
# Launch a server on linux phone
python3 -m http.server 53317

# Access served files from another machine
wget xxx
```

**Comment by vogonwann** [comment]
```sudo lsof -i -P -n | grep 53317```

no

```
# Launch a server on linux phone
python3 -m http.server 53317
 
# Access served files from another machine
wget xxx
```

cannot access even with firewall completely disabled

**Comment by realth000** [comment]
> ```sudo lsof -i -P -n | grep 53317```
> 
> no
> 
> ```
> # Launch a server on linux phone
> python3 -m http.server 53317
>  
> # Access served files from another machine
> wget xxx
> ```
> 
> cannot access even with firewall completely disabled

Clear all iptables policy and have another try:

``` bash
sudo iptables -F
```

**Comment by vogonwann** [comment]
> Clear all iptables policy and have another try:

No, still no connection to the phone.

**Comment by sunshinehot** [comment]
I have also experienced this on Ubuntu Touch Pixel 3a xl.

**Comment by proycon** [comment]
Similar issue on postmarketos edge, oneplus-enchilada, flatpak with xdg-desktop-portal-wlr. I do get a dbus-related socket error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Connection failed (OS Error: No such file or directory, errno = 2), address = /var/run/dbus/system_bus_socket, port = 0
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721)
#1      _NativeSocket.connect (dart:io-patch/socket_patch.dart:984)
#2      _RawSocket.connect (dart:io-patch/socket_patch.dart:1908)
#3      RawSocket.connect (dart:io-patch/socket_patch.dart:21)
#4      DBusClient._openSocket (package:dbus/src/dbus_client.dart:780)
#5      DBusClient._connect (package:dbus/src/dbus_client.dart:800)
#6      DBusClient.callMethod (package:dbus/src/dbus_client.dart:620)
#7      DBusClient.getNameOwner (package:dbus/src/dbus_client.dart:461)
#8      DBusClient._findUniqueName (package:dbus/src/dbus_client.dart:637)
#9      DBusSignalStream._onListen (package:dbus/src/dbus_client.dart:132)
#10     _runGuarded (dart:async/stream_controller.dart:824)
#11     _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:207)
#12     _ControllerStream._createSubscription (dart:async/stream_controller.dart:837)
#13     _StreamImpl.listen (dart:async/stream_impl.dart:497)
#14     DBusSignalStream.listen (package:dbus/src/dbus_client.dart:124)
#15     new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:114)
#16     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:86)
#17     _ForwardingStream.listen (dart:async/stream_pipe.dart:81)
#18     NetworkManagerClient.connect (package:nm/src/network_manager_client.dart:2303)
#19     NetworkInfoPlusLinuxPlugin._getConnectionValue (package:network_info_plus/src/network_info_plus_linux.dart:87)
#20     NetworkInfoPlusLinuxPlugin.getWifiIP (package:network_info_plus/src/network_info_plus_linux.dart:34)
#21     NetworkInfo.getWifiIP (package:network_info_plus/network_info_plus.dart:63)
#22     _getIp (package:localsend_app/provider/local_ip_provider.dart:89)
#23     FetchLocalIpAction.reduce (package:localsend_app/provider/local_ip_provider.dart:73)
#24     AsyncReduxAction.wrapReduce (package:refena/src/action/redux_action.dart:280)
#25     AsyncReduxAction.internalWrapReduce (package:refena/src/action/redux_action.dart:286)
#26     ReduxNotifier._dispatchAsyncWithResult (package:refena/src/notifier/types/redux_notifier.dart:329)
<asynchronous suspension>
#27     ReduxNotifier.dispatchAsync (package:refena/src/notifier/types/redux_notifier.dart:209)
<asynchronous suspension>

flutter: 2025-07-30 22:50:41.630031    [INFO] [Server] Server started. (Port: 53317, HTTPS only)
```

The server actually did start in my case, but my two postmarketos devices (on same wifi) aren't seeing eachother and can't connect to eachother. Despite there being no firewall. Problem also appears with python3 -m http.server 53317 so it's possibly not a localsend issue but an Alpine/postmarketos one.

**Comment by proycon** [comment]
Ok fellow postmarketOS users, it was a indeed a firewall issue. PostmarketOS uses nftables and is set fairly restrictive by default (for good reason on a mobile device):

Put the following in `/etc/nftables.d/50_localsend.nft` (new file):

```
#!/usr/sbin/nft -f

table inet filter {
	chain input {
          # allow incoming broadcast and multicast
          pkttype { broadcast,multicast} accept

          tcp dport 53317 accept comment "accept localsend"
	}
}
```

Then restart the firewall:  `sudo rc-service nftables restart` (for openrc based systems, for the upcoming releases with systemd it will probably be `sudo systemctl restart nftables`)
