### ISSUE TITLE
Old Android Verion can't run the app.

### ISSUE THREAD

**Issue by DantesLin** [localsend/localsend#1921]
### Describe the bug

Hello, I've successfully installed the latest version of the "LocalSend-1.15.4-android-google-play.apk" on my Android tablet, which is running Android version 5.1.1. However, I'm encountering an issue with the LocalSend application. Whenever I attempt to open it, the app crashes immediately. Could you please assist me with this issue?

### To reproduce

1. after installed LocalSend-1.15.4-android-google-play.apk;
2. Click on the app, it will crash.

### Expected behavior

If the developer still supports this Android version, could you please provide some assistance? If not, that's fine too. Thank you very much.

**Comment by Edger** [comment]
+1

**Comment by Gudine** [comment]
Same thing is happening to me on my Samsung Galaxy J5, running Android 6, ARM32. It's worth noting that the last version of the app to work is 1.15.1.

**Comment by schrmh** [comment]
Interestingly for me 1.17.0 works on a armv7 tablet that tends to have some problems.
But on a armv7 phone that I decided to spend some time on this app has exactly this problem here.
I tried all the architecture compatible apks for 1.15.2 and it crashed:
Logcat (with LocalSend-1.15.2-android--fix-back-gesture.apk):
[logcat_localsend.log](https://github.com/user-attachments/files/20827030/logcat_localsend.log)
I opened the app three times.
I think this is the relevant stuff:
```
V/WindowManager( 2169): Adding window Window{163ca144 u0 org.localsend.localsend_app/org.localsend.localsend_app.MainActivity} at 3 of 11 (before Window{2a25f97b u0 Starting org.localsend.localsend_app})
I/art     (28232): Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback>
I/art     (28232): Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$DistinctSidecarElementCallback>
I/art     (28232): Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$TranslatingCallback>
I/art     (28232): Rejecting re-init on previously-failed class java.lang.Class<androidx.window.layout.SidecarCompat$TranslatingCallback>
I/SurfaceFlinger(  253): FPS: 26
I/OpenGLRenderer(28232): Initialized EGL, version 1.4
D/OpenGLRenderer(28232): Enabling debug mode 0
I/qdutils (28232): PartialUpdate status: Disabled
I/qdutils (28232): Left Align: 0
I/qdutils (28232): Width Align: 0
I/qdutils (28232): Top Align: 0
I/qdutils (28232): Height Align: 0
I/qdutils (28232): Min ROI Width: 0
I/qdutils (28232): Min ROI Height: 0
I/qdutils (28232): Needs ROI Merge: 0
I/qdutils (28232): Dynamic Fps: Disabled
I/qdutils (28232): Min Panel fps: 0
I/qdutils (28232): Max Panel fps: 0
V/WindowManager( 2169): Adding window Window{c52362 u0 SurfaceView} at 3 of 12 (before Window{163ca144 u0 org.localsend.localsend_app/org.localsend.localsend_app.MainActivity})
F/libc    (28232): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb73a2000 in tid 28255 (1.ui)
I/libc    (28232): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
I/LatinIME( 6701): onFinishInput
I/WindowState( 2169): WIN DEATH: Window{163ca144 u0 org.localsend.localsend_app/org.localsend.localsend_app.MainActivity}
W/WindowManager( 2169): Force-removing child win Window{c52362 u0 SurfaceView} from container Window{163ca144 u0 org.localsend.localsend_app/org.localsend.localsend_app.MainActivity}
W/WindowManager( 2169): Failed looking up window
W/WindowManager( 2169): java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@2f8b922d does not exist
W/WindowManager( 2169): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8607)
W/WindowManager( 2169): 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8598)
W/WindowManager( 2169): 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1142)
W/WindowManager( 2169): 	at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState( 2169): WIN DEATH: null
I/Zygote  (  289): Process 28232 exited due to signal (11)
I/ActivityManager( 2169): Process org.localsend.localsend_app (pid 28232) has died
W/ActivityManager( 2169): Force removing ActivityRecord{3b3ded03 u0 org.localsend.localsend_app/.MainActivity t90}: app died, no saved state
D/Launcher3(13729): Launcher, Time spent in onResume: 1
W/InputMethodManagerService( 2169): Got RemoteException sending setActive(false) notification to pid 28232 uid 10134
I/LatinIME( 6701): onFinishInput
I/Timeline(13729): Timeline: Activity_idle id: android.os.BinderProxy@2daacca time:12914065
D/PowerManagerService( 2169): releaseWakeLockInternal: lock=559567194 [ActivityManager-Launch], flags=0x0, total_time=1301ms
I/Timeline( 2169): Timeline: Activity_windows_visible id: ActivityRecord{efb4f68 u0 com.android.launcher3/.Launcher t50} time:12914225
D/UsbDeviceManager( 2169): onReceive - mUsbNotificationId == charging ? false, mSettingUsbCharging: false mPlugType = 2 mConnected = true mCurrentFunctions = mtp,adb mDefaultFunctions = mtp,adb
D/BatteryMeterView( 3629): draw = 100
D/BatteryMeterView( 3629): draw: tracker.plugged = true, tracker.level = 100, tracker.temperature = 320, tracker.status = 5
I/SurfaceFlinger(  253): FPS: 17
I/Timeline(13729): Timeline: Activity_launch_request id:org.localsend.localsend_app time:12915886
D/PKMS    ( 2169): resolveIntent query=[ResolveInfo{205613ae org.localsend.localsend_app/.MainActivity m=0x0}]
```
