### ISSUE TITLE
Compilation Error: 'FFS_IS_MESSAGE_CODEC' [-Werror,-Wunused-function]

### ISSUE THREAD

**Issue by kero990** [localsend/localsend#2014]
### Describe the bug

Attempting to compile the arm64 version on Debian 10, as I need glibc < 2.28. Previous versions have been fine, but now the latest code is throwing the error 'FFS_IS_MESSAGE_CODEC' [-Werror,-Wunused-function].
This seems to be just a common warning level issue in C code, but unfortunately, I don't know how to exclude it in Flutter. I tried adding CXXFLAGS and using environment variables in the CMakeLists file under the linux folder, but none of them worked.

### To reproduce

Following the build method in GitHub Actions to configure the environment, only the system was replaced with Debian 10.

### Expected behavior

需要在glibc<2.28的环境中使用

**Comment by Tienisto** [comment]
Have you tried to run flutter build in verbose mode? Can you try to build a Flutter hello world app using the latest Flutter 3.24.4 version?

**Comment by kero990** [comment]
Oh, I forgot to post the detailed error information.
```
~/localsend/app/linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux/linux/messages.g.cc:234:1: error: unused function 'FFS_IS_MESSAGE_CODEC' [-Werror,-Wunused-function]             
~/localsend/app/linux/flutter/ephemeral/.plugin_symlinks/file_selector_linux/linux/messages.g.cc:436:1: error: unused function 'FFS_IS_FILE_SELECTOR_API' [-Werror,-Wunused-function]         
Building Linux application...                                           
Build process failed
```
In verbose mode, the error information is the same as above, but there is more information after `Build process failed`.

```
[   +8 ms] Build process failed
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:210:5)
           <asynchronous suspension>
           #2      buildLinux (package:flutter_tools/src/linux/build_linux.dart:83:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand
(package:flutter_tools/src/commands/build_linux.dart:87:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>
           
           
[ +252 ms] ensureAnalyticsSent: 247ms
[        ] Running 1 shutdown hook
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by kero990** [comment]
Since I followed the compilation process of GitHub Actions and created the compilation environment from scratch, I am confident that it is correct.
git clone -b 3.24.4 https://github.com/flutter/flutter

**Comment by Tienisto** [comment]
It seems that the [file_selector_linux](https://pub.dev/packages/file_selector_linux) dependency is causing problems. Maybe you can try to downgrade it to `v0.9.2+1`.
You can do this by overriding it in `pubspec.yaml`:

```yaml
dependency_overrides:
  file_selector_linux: 0.9.2+1

**Comment by kero990** [comment]
According to your instructions, I downgraded the version of file_selector_linux in pubspec.yaml to 0.9.2+1, but the error remains unchanged. I also tried completely removing localsend, recloning the project, modifying pubspec.yaml, and then running pub get and build, but the result was the same. I'm not sure if this plugin is on GitHub, but maybe I can check the issues there.

**Comment by Tienisto** [comment]
First, you need to check if it's an error from Flutter or from the plugin. Here a hello world app might help (`flutter create hello_world`).

If it compiles, then you know that the plugin is causing the error.

**Comment by kero990** [comment]
> First, you need to check if it's an error from Flutter or from the plugin. Here a hello world app might help (`flutter create hello_world`).
> 
> If it compiles, then you know that the plugin is causing the error.

Please don't doubt my Flutter environment. I've gotten the same results on several machines (clean Debian 10 Docker environments), yes, including x86 architecture, not just arm64.

It can even be reproduced on GitHub Actions, as long as you use `container: debian:10`, although the error message doesn't show up.
https://github.com/kero990/auto-actions/actions/runs/11734630646/job/32690984389

**Comment by Tienisto** [comment]
I don't question if your Debian 10 is clean, I question if the newest Flutter version supports Debian 10 in the first place.

Regardless, I don't know how to fix this because this is a native error. Either a plugin or Flutter caused this error, not LocalSend itself.

**Comment by kero990** [comment]
I raised an issue in a Flutter project, 
https://github.com/flutter/flutter/issues/158900
and the reply linked to another one.
https://github.com/flutter/flutter/issues/153083
