### ISSUE TITLE
Bug report for 1.16.1  when use macOS 12.7.6

### ISSUE THREAD

**Issue by xiehaowei** [localsend/localsend#2034]
### Describe the bug

```
LocalSend 1.16.1 (56)

Error: RhttpError.rhttpUnknownError(field0: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } } })

#0      SimpleDecoder.decode (package:flutter_rust_bridge/src/codec/base.dart:32)
#1      SseCodec._decode (package:flutter_rust_bridge/src/codec/sse.dart:45)
#2      SseCodec.decodeWireSyncType (package:flutter_rust_bridge/src/codec/sse.dart:40)
#3      BaseHandler.executeSync (package:flutter_rust_bridge/src/main_components/handler.dart:34)
#4      RustLibApiImpl.crateApiHttpRegisterClientSync (package:rhttp/src/rust/frb_generated.dart:511)
#5      registerClientSync (package:rhttp/src/rust/api/http.dart:23)
#6      new RhttpClient.createSync (package:rhttp/src/client/rhttp_client.dart:62)
#7      createRhttpClient (package:localsend_app/util/rhttp.dart:71)
#8      preInit (package:localsend_app/config/init.dart:81)
<asynchronous suspension>
#9      main (package:localsend_app/main.dart:23)
<asynchronous suspension>

```

### To reproduce

1. install from mac App store,macOS v12.7.6
2. local send version 1.16.1
3. open app ,and report error 
`Error: RhttpError.rhttpUnknownError(field0: reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } } })`

### Expected behavior

normal use

### Screenshots

<img width="800" alt="image" src="https://github.com/user-attachments/assets/d3c38114-e612-413d-8568-bee465d4316d">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/3b1b2392-abfd-4a3b-acbb-c23ed022be7c">

### Desktop (please complete the following information)

-OS mac 12.7.6

**Comment by jzhudev** [comment]
same issue on Mac 14.3 (23D56)

**Comment by Tabrellik** [comment]
Running into the same issue on Ubuntu 24.10 using both the '.deb' and '.tar.gz' download options. I had it functional on Snap but is now not launching (but that might be a separate issue)

**Comment by rinvay** [comment]
Same issue on Mac OS 11.7

**Comment by IlPinguino7** [comment]
Same issue here on Macos 13.7.2, no matter if installed from app store or via dmg. Localsend 1.16.0 works fine instead.

**Comment by saurabh12453** [comment]
I’ll figure it out.

**Comment by tdwong** [comment]
exact same configuration and exact same issue as OP.  Building the app with `brew install --cask localsend` yielded the same result.
