### ISSUE TITLE
[macOS] Unhandled Exception: ProcessException: Too many open files when click SendTab/File

### ISSUE THREAD

**Issue by hyiso** [localsend/localsend#41]
Steps to reproduce:

1. clone this repo
2. flutter pub get & flutter pub run build_runner build
3. flutter run on macos
4. click SendTab/File

Stacktrace:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: ProcessException: Too many open files
  Command: which osascript
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:401:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:578:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      runExecutableWithArguments (package:file_picker/src/utils.dart:49:39)
#5      isExecutableOnPath (package:file_picker/src/utils.dart:58:22)
#6      FilePickerMacOS.pickFiles (package:file_picker/src/file_picker_macos.dart:18:37)
#7      FilePickerOption.select (package:localsend_app/util/file_picker.dart:35:50)
#8      _SendTabState.build.<anonymous closure>.<anonymous closure> (package:localsend_app/pages/tabs/send_tab.dart:94:51)
#9      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1072:21)
#10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
#11     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
#12     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
#13     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:239:7)
#14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:615:9)
#15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#16     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#17     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
#18     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#19     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#20     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:460:19)
#21     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:440:22)
#22     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:337:11)
#23     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:395:7)
#24     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:357:5)
#25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:314:7)
#26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:295:7)
#27     _invoke1 (dart:ui/hooks.dart:167:13)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:341:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

**Comment by hyiso** [comment]
Maybe related to https://github.com/flutter/flutter/issues/71345, seems to be a problem of macOS.
