### ISSUE TITLE
Flatpak version does not allow drag-and-drop outside of Downloads directory

### ISSUE THREAD

**Issue by thjxs** [localsend/localsend#513]
### Describe the bug

Drag file not working
[Screencast from 2023-06-07 16-26-06.webm](https://github.com/localsend/localsend/assets/26674785/4d7e50ca-2f7d-4233-b1de-be1472a7e1c5)

### To reproduce

See video above, it seems works at `~/Downloads`, where as LocalSend destination directory

### Expected behavior

Support drag file on fedora 38

### Desktop (please complete the following information)

OS: Fedora Linux 38 (Workstation Edition)

**Comment by Tienisto** [comment]
Are you using flatpak?

**Comment by thjxs** [comment]
Yes

**Comment by thjxs** [comment]
Run `flatpak run org.localsend.localsend_app -–filesystem=xdg-documents`
I got this error
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot retrieve length of file, path = '/home/tan/Documents/example.docx' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:42)
#1      _File.length.<anonymous closure> (dart:io/file_impl.dart:372)
<asynchronous suspension>
#2      CrossFileConverters.convertXFile (package:localsend_app/provider/selection/selected_sending_files_provider.dart:140)
<asynchronous suspension>
#3      SelectedSendingFilesNotifier.addFiles (package:localsend_app/provider/selection/selected_sending_files_provider.dart:60)
<asynchronous suspension>
#4      _HomePageState.build.<anonymous closure> (package:localsend_app/pages/home_page.dart:99)
<asynchronous suspension>
```

**Comment by plutack1** [comment]
The aur package also doesn’t support multiple select drag and drop. A single folder works though.

**Comment by Tienisto** [comment]
By default, the flatpak version only has access to the "Dowloads" folder. You need to add full access: #256

**Comment by KraXen72** [comment]
i fixed this on fedora 40 using the flatpak by using Flatseal, and adding the following paths to the `Other files` permission:
`home`, and two mount points for my ntfs partitions (these will be different for you according to your fstab/current mount): `/media/win` and `/media/data`.
![image](https://github.com/localsend/localsend/assets/21956756/e8fdc6b1-3dd1-4087-b7df-4533b176ab9a)

**Comment by rsp4jack** [comment]
@Tienisto 

> It seems that the app does not have read permission if using drag-and-drop.

The app does not have to have the read permission. Reading the files can be achieved through [FileTransfer API](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileTransfer.html).
