### ISSUE TITLE
Unable to send mkv file (regardless of size)

### ISSUE THREAD

**Issue by q962** [localsend/localsend#567]
### Describe the bug

Observed result: as long as the file with the suffix of mkv cannot be sent.
Other files are fine

```
flutter: Sending aaa（复件）.mkv
flutter: *** Request ***
flutter: uri: https://192.168.1.3:53317/api/localsend/v2/upload?sessionId=66e22282-f2da-4e5e-9c54-30aa1a62d067&fileId=e91f17ed-4af6-4fd7-9e56-caa4ab35c634&token=7c86403f-7d4c-46b1-affb-76b30b3fcd21
flutter: data:
flutter: Instance of '_FileStream'
flutter:
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:89)
<asynchronous suspension>
#1      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20)
<asynchronous suspension>

```

### To reproduce

Desktop => Smartphone
send file.mkv

### Expected behavior

I don't get it, is there anything special about the mkv file?
Isn't it all a bunch of data?

Other files are sent fine, and mkv should be fine too.

### Screenshots

![image](https://github.com/localsend/localsend/assets/15686075/f82c37f2-c6ae-46ef-a8c5-4a8b5d82ef3d)
![image](https://github.com/localsend/localsend/assets/15686075/5cec8076-fb14-4d3a-b357-8cc8f1e411ef)

### Desktop (please complete the following information)

- OS: flatpak
- Version: 1.10.0

### Smartphone (please complete the following information)

- Device: iphone14ProMax
- OS: 16.2
- Version: 1.10.0

**Comment by Tienisto** [comment]
Have you tried to rename the file name?

**Comment by q962** [comment]
Yes, pay attention to the pictures in the screenshot column.

**Comment by daddycool322** [comment]
Same

**Comment by Loyalsoldier** [comment]
https://github.com/localsend/localsend/issues/1309#issuecomment-2568680226
